/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_shellUtils.h"

static const char* CMockString_ShellUtils_addHistory = "ShellUtils_addHistory";
static const char* CMockString_ShellUtils_autocomplete = "ShellUtils_autocomplete";
static const char* CMockString_ShellUtils_compare = "ShellUtils_compare";
static const char* CMockString_ShellUtils_historyDown = "ShellUtils_historyDown";
static const char* CMockString_ShellUtils_historyUp = "ShellUtils_historyUp";
static const char* CMockString_cmd = "cmd";
static const char* CMockString_size = "size";
static const char* CMockString_str = "str";
static const char* CMockString_str1 = "str1";
static const char* CMockString_str2 = "str2";

typedef struct _CMOCK_ShellUtils_compare_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  _Bool ReturnVal;
  int CallOrder;
  char* Expected_str1;
  char* Expected_str2;

} CMOCK_ShellUtils_compare_CALL_INSTANCE;

typedef struct _CMOCK_ShellUtils_autocomplete_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  _Bool ReturnVal;
  int CallOrder;
  char* Expected_str;
  uint16_t* Expected_size;

} CMOCK_ShellUtils_autocomplete_CALL_INSTANCE;

typedef struct _CMOCK_ShellUtils_addHistory_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  char* Expected_cmd;

} CMOCK_ShellUtils_addHistory_CALL_INSTANCE;

typedef struct _CMOCK_ShellUtils_historyUp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  _Bool ReturnVal;
  int CallOrder;
  char* Expected_str;
  uint16_t* Expected_size;

} CMOCK_ShellUtils_historyUp_CALL_INSTANCE;

typedef struct _CMOCK_ShellUtils_historyDown_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  _Bool ReturnVal;
  int CallOrder;
  char* Expected_str;
  uint16_t* Expected_size;

} CMOCK_ShellUtils_historyDown_CALL_INSTANCE;

static struct mock_shellUtilsInstance
{
  char ShellUtils_compare_IgnoreBool;
  _Bool ShellUtils_compare_FinalReturn;
  char ShellUtils_compare_CallbackBool;
  CMOCK_ShellUtils_compare_CALLBACK ShellUtils_compare_CallbackFunctionPointer;
  int ShellUtils_compare_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ShellUtils_compare_CallInstance;
  char ShellUtils_autocomplete_IgnoreBool;
  _Bool ShellUtils_autocomplete_FinalReturn;
  char ShellUtils_autocomplete_CallbackBool;
  CMOCK_ShellUtils_autocomplete_CALLBACK ShellUtils_autocomplete_CallbackFunctionPointer;
  int ShellUtils_autocomplete_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ShellUtils_autocomplete_CallInstance;
  char ShellUtils_addHistory_IgnoreBool;
  char ShellUtils_addHistory_CallbackBool;
  CMOCK_ShellUtils_addHistory_CALLBACK ShellUtils_addHistory_CallbackFunctionPointer;
  int ShellUtils_addHistory_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ShellUtils_addHistory_CallInstance;
  char ShellUtils_historyUp_IgnoreBool;
  _Bool ShellUtils_historyUp_FinalReturn;
  char ShellUtils_historyUp_CallbackBool;
  CMOCK_ShellUtils_historyUp_CALLBACK ShellUtils_historyUp_CallbackFunctionPointer;
  int ShellUtils_historyUp_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ShellUtils_historyUp_CallInstance;
  char ShellUtils_historyDown_IgnoreBool;
  _Bool ShellUtils_historyDown_FinalReturn;
  char ShellUtils_historyDown_CallbackBool;
  CMOCK_ShellUtils_historyDown_CALLBACK ShellUtils_historyDown_CallbackFunctionPointer;
  int ShellUtils_historyDown_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ShellUtils_historyDown_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_shellUtils_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.ShellUtils_compare_CallInstance;
  if (Mock.ShellUtils_compare_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ShellUtils_compare);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ShellUtils_compare_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.ShellUtils_autocomplete_CallInstance;
  if (Mock.ShellUtils_autocomplete_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ShellUtils_autocomplete);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ShellUtils_autocomplete_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.ShellUtils_addHistory_CallInstance;
  if (Mock.ShellUtils_addHistory_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ShellUtils_addHistory);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ShellUtils_addHistory_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.ShellUtils_historyUp_CallInstance;
  if (Mock.ShellUtils_historyUp_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ShellUtils_historyUp);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ShellUtils_historyUp_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.ShellUtils_historyDown_CallInstance;
  if (Mock.ShellUtils_historyDown_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ShellUtils_historyDown);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ShellUtils_historyDown_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_shellUtils_Init(void)
{
  mock_shellUtils_Destroy();
}

void mock_shellUtils_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

_Bool ShellUtils_compare(char* str1, char* str2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ShellUtils_compare_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ShellUtils_compare);
  cmock_call_instance = (CMOCK_ShellUtils_compare_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ShellUtils_compare_CallInstance);
  Mock.ShellUtils_compare_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_compare_CallInstance);
  if (Mock.ShellUtils_compare_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ShellUtils_compare_FinalReturn;
    memcpy((void*)(&Mock.ShellUtils_compare_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ShellUtils_compare_CallbackBool &&
      Mock.ShellUtils_compare_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.ShellUtils_compare_CallbackFunctionPointer(str1, str2, Mock.ShellUtils_compare_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_compare,CMockString_str1);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_str1, str1, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_compare,CMockString_str2);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_str2, str2, cmock_line, CMockStringMismatch);
  }
  if (Mock.ShellUtils_compare_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ShellUtils_compare_CallbackFunctionPointer(str1, str2, Mock.ShellUtils_compare_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ShellUtils_compare(CMOCK_ShellUtils_compare_CALL_INSTANCE* cmock_call_instance, char* str1, char* str2);
void CMockExpectParameters_ShellUtils_compare(CMOCK_ShellUtils_compare_CALL_INSTANCE* cmock_call_instance, char* str1, char* str2)
{
  cmock_call_instance->Expected_str1 = str1;
  cmock_call_instance->Expected_str2 = str2;
}

void ShellUtils_compare_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_compare_CALL_INSTANCE));
  CMOCK_ShellUtils_compare_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_compare_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_compare_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_compare_CallInstance, cmock_guts_index);
  Mock.ShellUtils_compare_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ShellUtils_compare_IgnoreBool = (char)1;
}

void ShellUtils_compare_CMockStopIgnore(void)
{
  if(Mock.ShellUtils_compare_IgnoreBool)
    Mock.ShellUtils_compare_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_compare_CallInstance);
  Mock.ShellUtils_compare_IgnoreBool = (char)0;
}

void ShellUtils_compare_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* str1, char* str2, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_compare_CALL_INSTANCE));
  CMOCK_ShellUtils_compare_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_compare_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_compare_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_compare_CallInstance, cmock_guts_index);
  Mock.ShellUtils_compare_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_ShellUtils_compare(cmock_call_instance, str1, str2);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void ShellUtils_compare_AddCallback(CMOCK_ShellUtils_compare_CALLBACK Callback)
{
  Mock.ShellUtils_compare_IgnoreBool = (char)0;
  Mock.ShellUtils_compare_CallbackBool = (char)1;
  Mock.ShellUtils_compare_CallbackFunctionPointer = Callback;
}

void ShellUtils_compare_Stub(CMOCK_ShellUtils_compare_CALLBACK Callback)
{
  Mock.ShellUtils_compare_IgnoreBool = (char)0;
  Mock.ShellUtils_compare_CallbackBool = (char)0;
  Mock.ShellUtils_compare_CallbackFunctionPointer = Callback;
}

_Bool ShellUtils_autocomplete(char* str, uint16_t* size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ShellUtils_autocomplete_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ShellUtils_autocomplete);
  cmock_call_instance = (CMOCK_ShellUtils_autocomplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ShellUtils_autocomplete_CallInstance);
  Mock.ShellUtils_autocomplete_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_autocomplete_CallInstance);
  if (Mock.ShellUtils_autocomplete_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ShellUtils_autocomplete_FinalReturn;
    memcpy((void*)(&Mock.ShellUtils_autocomplete_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ShellUtils_autocomplete_CallbackBool &&
      Mock.ShellUtils_autocomplete_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.ShellUtils_autocomplete_CallbackFunctionPointer(str, size, Mock.ShellUtils_autocomplete_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_autocomplete,CMockString_str);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_str, str, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_autocomplete,CMockString_size);
    if (cmock_call_instance->Expected_size == NULL)
      { UNITY_TEST_ASSERT_NULL(size, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_size, size, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.ShellUtils_autocomplete_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ShellUtils_autocomplete_CallbackFunctionPointer(str, size, Mock.ShellUtils_autocomplete_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ShellUtils_autocomplete(CMOCK_ShellUtils_autocomplete_CALL_INSTANCE* cmock_call_instance, char* str, uint16_t* size);
void CMockExpectParameters_ShellUtils_autocomplete(CMOCK_ShellUtils_autocomplete_CALL_INSTANCE* cmock_call_instance, char* str, uint16_t* size)
{
  cmock_call_instance->Expected_str = str;
  cmock_call_instance->Expected_size = size;
}

void ShellUtils_autocomplete_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_autocomplete_CALL_INSTANCE));
  CMOCK_ShellUtils_autocomplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_autocomplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_autocomplete_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_autocomplete_CallInstance, cmock_guts_index);
  Mock.ShellUtils_autocomplete_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ShellUtils_autocomplete_IgnoreBool = (char)1;
}

void ShellUtils_autocomplete_CMockStopIgnore(void)
{
  if(Mock.ShellUtils_autocomplete_IgnoreBool)
    Mock.ShellUtils_autocomplete_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_autocomplete_CallInstance);
  Mock.ShellUtils_autocomplete_IgnoreBool = (char)0;
}

void ShellUtils_autocomplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* str, uint16_t* size, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_autocomplete_CALL_INSTANCE));
  CMOCK_ShellUtils_autocomplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_autocomplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_autocomplete_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_autocomplete_CallInstance, cmock_guts_index);
  Mock.ShellUtils_autocomplete_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_ShellUtils_autocomplete(cmock_call_instance, str, size);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void ShellUtils_autocomplete_AddCallback(CMOCK_ShellUtils_autocomplete_CALLBACK Callback)
{
  Mock.ShellUtils_autocomplete_IgnoreBool = (char)0;
  Mock.ShellUtils_autocomplete_CallbackBool = (char)1;
  Mock.ShellUtils_autocomplete_CallbackFunctionPointer = Callback;
}

void ShellUtils_autocomplete_Stub(CMOCK_ShellUtils_autocomplete_CALLBACK Callback)
{
  Mock.ShellUtils_autocomplete_IgnoreBool = (char)0;
  Mock.ShellUtils_autocomplete_CallbackBool = (char)0;
  Mock.ShellUtils_autocomplete_CallbackFunctionPointer = Callback;
}

void ShellUtils_addHistory(char* cmd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ShellUtils_addHistory_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ShellUtils_addHistory);
  cmock_call_instance = (CMOCK_ShellUtils_addHistory_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ShellUtils_addHistory_CallInstance);
  Mock.ShellUtils_addHistory_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_addHistory_CallInstance);
  if (Mock.ShellUtils_addHistory_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.ShellUtils_addHistory_CallbackBool &&
      Mock.ShellUtils_addHistory_CallbackFunctionPointer != NULL)
  {
    Mock.ShellUtils_addHistory_CallbackFunctionPointer(cmd, Mock.ShellUtils_addHistory_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_addHistory,CMockString_cmd);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_cmd, cmd, cmock_line, CMockStringMismatch);
  }
  if (Mock.ShellUtils_addHistory_CallbackFunctionPointer != NULL)
  {
    Mock.ShellUtils_addHistory_CallbackFunctionPointer(cmd, Mock.ShellUtils_addHistory_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_ShellUtils_addHistory(CMOCK_ShellUtils_addHistory_CALL_INSTANCE* cmock_call_instance, char* cmd);
void CMockExpectParameters_ShellUtils_addHistory(CMOCK_ShellUtils_addHistory_CALL_INSTANCE* cmock_call_instance, char* cmd)
{
  cmock_call_instance->Expected_cmd = cmd;
}

void ShellUtils_addHistory_CMockIgnore(void)
{
  Mock.ShellUtils_addHistory_IgnoreBool = (char)1;
}

void ShellUtils_addHistory_CMockStopIgnore(void)
{
  Mock.ShellUtils_addHistory_IgnoreBool = (char)0;
}

void ShellUtils_addHistory_CMockExpect(UNITY_LINE_TYPE cmock_line, char* cmd)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_addHistory_CALL_INSTANCE));
  CMOCK_ShellUtils_addHistory_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_addHistory_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_addHistory_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_addHistory_CallInstance, cmock_guts_index);
  Mock.ShellUtils_addHistory_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_ShellUtils_addHistory(cmock_call_instance, cmd);
}

void ShellUtils_addHistory_AddCallback(CMOCK_ShellUtils_addHistory_CALLBACK Callback)
{
  Mock.ShellUtils_addHistory_IgnoreBool = (char)0;
  Mock.ShellUtils_addHistory_CallbackBool = (char)1;
  Mock.ShellUtils_addHistory_CallbackFunctionPointer = Callback;
}

void ShellUtils_addHistory_Stub(CMOCK_ShellUtils_addHistory_CALLBACK Callback)
{
  Mock.ShellUtils_addHistory_IgnoreBool = (char)0;
  Mock.ShellUtils_addHistory_CallbackBool = (char)0;
  Mock.ShellUtils_addHistory_CallbackFunctionPointer = Callback;
}

_Bool ShellUtils_historyUp(char* str, uint16_t* size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ShellUtils_historyUp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ShellUtils_historyUp);
  cmock_call_instance = (CMOCK_ShellUtils_historyUp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ShellUtils_historyUp_CallInstance);
  Mock.ShellUtils_historyUp_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_historyUp_CallInstance);
  if (Mock.ShellUtils_historyUp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ShellUtils_historyUp_FinalReturn;
    memcpy((void*)(&Mock.ShellUtils_historyUp_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ShellUtils_historyUp_CallbackBool &&
      Mock.ShellUtils_historyUp_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.ShellUtils_historyUp_CallbackFunctionPointer(str, size, Mock.ShellUtils_historyUp_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_historyUp,CMockString_str);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_str, str, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_historyUp,CMockString_size);
    if (cmock_call_instance->Expected_size == NULL)
      { UNITY_TEST_ASSERT_NULL(size, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_size, size, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.ShellUtils_historyUp_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ShellUtils_historyUp_CallbackFunctionPointer(str, size, Mock.ShellUtils_historyUp_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ShellUtils_historyUp(CMOCK_ShellUtils_historyUp_CALL_INSTANCE* cmock_call_instance, char* str, uint16_t* size);
void CMockExpectParameters_ShellUtils_historyUp(CMOCK_ShellUtils_historyUp_CALL_INSTANCE* cmock_call_instance, char* str, uint16_t* size)
{
  cmock_call_instance->Expected_str = str;
  cmock_call_instance->Expected_size = size;
}

void ShellUtils_historyUp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_historyUp_CALL_INSTANCE));
  CMOCK_ShellUtils_historyUp_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_historyUp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_historyUp_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_historyUp_CallInstance, cmock_guts_index);
  Mock.ShellUtils_historyUp_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ShellUtils_historyUp_IgnoreBool = (char)1;
}

void ShellUtils_historyUp_CMockStopIgnore(void)
{
  if(Mock.ShellUtils_historyUp_IgnoreBool)
    Mock.ShellUtils_historyUp_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_historyUp_CallInstance);
  Mock.ShellUtils_historyUp_IgnoreBool = (char)0;
}

void ShellUtils_historyUp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* str, uint16_t* size, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_historyUp_CALL_INSTANCE));
  CMOCK_ShellUtils_historyUp_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_historyUp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_historyUp_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_historyUp_CallInstance, cmock_guts_index);
  Mock.ShellUtils_historyUp_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_ShellUtils_historyUp(cmock_call_instance, str, size);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void ShellUtils_historyUp_AddCallback(CMOCK_ShellUtils_historyUp_CALLBACK Callback)
{
  Mock.ShellUtils_historyUp_IgnoreBool = (char)0;
  Mock.ShellUtils_historyUp_CallbackBool = (char)1;
  Mock.ShellUtils_historyUp_CallbackFunctionPointer = Callback;
}

void ShellUtils_historyUp_Stub(CMOCK_ShellUtils_historyUp_CALLBACK Callback)
{
  Mock.ShellUtils_historyUp_IgnoreBool = (char)0;
  Mock.ShellUtils_historyUp_CallbackBool = (char)0;
  Mock.ShellUtils_historyUp_CallbackFunctionPointer = Callback;
}

_Bool ShellUtils_historyDown(char* str, uint16_t* size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ShellUtils_historyDown_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ShellUtils_historyDown);
  cmock_call_instance = (CMOCK_ShellUtils_historyDown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ShellUtils_historyDown_CallInstance);
  Mock.ShellUtils_historyDown_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_historyDown_CallInstance);
  if (Mock.ShellUtils_historyDown_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ShellUtils_historyDown_FinalReturn;
    memcpy((void*)(&Mock.ShellUtils_historyDown_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.ShellUtils_historyDown_CallbackBool &&
      Mock.ShellUtils_historyDown_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.ShellUtils_historyDown_CallbackFunctionPointer(str, size, Mock.ShellUtils_historyDown_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_historyDown,CMockString_str);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_str, str, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_ShellUtils_historyDown,CMockString_size);
    if (cmock_call_instance->Expected_size == NULL)
      { UNITY_TEST_ASSERT_NULL(size, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_size, size, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.ShellUtils_historyDown_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ShellUtils_historyDown_CallbackFunctionPointer(str, size, Mock.ShellUtils_historyDown_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ShellUtils_historyDown(CMOCK_ShellUtils_historyDown_CALL_INSTANCE* cmock_call_instance, char* str, uint16_t* size);
void CMockExpectParameters_ShellUtils_historyDown(CMOCK_ShellUtils_historyDown_CALL_INSTANCE* cmock_call_instance, char* str, uint16_t* size)
{
  cmock_call_instance->Expected_str = str;
  cmock_call_instance->Expected_size = size;
}

void ShellUtils_historyDown_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_historyDown_CALL_INSTANCE));
  CMOCK_ShellUtils_historyDown_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_historyDown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_historyDown_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_historyDown_CallInstance, cmock_guts_index);
  Mock.ShellUtils_historyDown_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ShellUtils_historyDown_IgnoreBool = (char)1;
}

void ShellUtils_historyDown_CMockStopIgnore(void)
{
  if(Mock.ShellUtils_historyDown_IgnoreBool)
    Mock.ShellUtils_historyDown_CallInstance = CMock_Guts_MemNext(Mock.ShellUtils_historyDown_CallInstance);
  Mock.ShellUtils_historyDown_IgnoreBool = (char)0;
}

void ShellUtils_historyDown_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* str, uint16_t* size, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ShellUtils_historyDown_CALL_INSTANCE));
  CMOCK_ShellUtils_historyDown_CALL_INSTANCE* cmock_call_instance = (CMOCK_ShellUtils_historyDown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ShellUtils_historyDown_CallInstance = CMock_Guts_MemChain(Mock.ShellUtils_historyDown_CallInstance, cmock_guts_index);
  Mock.ShellUtils_historyDown_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_ShellUtils_historyDown(cmock_call_instance, str, size);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void ShellUtils_historyDown_AddCallback(CMOCK_ShellUtils_historyDown_CALLBACK Callback)
{
  Mock.ShellUtils_historyDown_IgnoreBool = (char)0;
  Mock.ShellUtils_historyDown_CallbackBool = (char)1;
  Mock.ShellUtils_historyDown_CallbackFunctionPointer = Callback;
}

void ShellUtils_historyDown_Stub(CMOCK_ShellUtils_historyDown_CALLBACK Callback)
{
  Mock.ShellUtils_historyDown_IgnoreBool = (char)0;
  Mock.ShellUtils_historyDown_CallbackBool = (char)0;
  Mock.ShellUtils_historyDown_CallbackFunctionPointer = Callback;
}

